SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT DATE_FORMAT(O.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
    FROM ONLINE_SALE O
    UNION ALL 
    SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d'), F.PRODUCT_ID, NULL, F.SALES_AMOUNT 
    FROM OFFLINE_SALE F
) AS combined_sales
WHERE MONTH(SALES_DATE) = 3
AND YEAR(SALES_DATE) = 2022
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
