-- 코드를 작성해주세요
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE S.NAME = "Python"
AND (D.SKILL_CODE & S.CODE) = S.CODE
OR S.NAME = "C#"
AND (D.SKILL_CODE & S.CODE) = S.CODE
ORDER BY ID;